In [23]:
import pandas as pd
import numpy as np 
import ast

In [24]:
def convert(value):
    X = []
    for i in ast.literal_eval(value):
        X.append(i['name'].replace(" ",''))
    return X

def convertOverview(value):
    return value.split(' ')

In [25]:
def convert3(value):
    X = []
    count = 0
    for i in ast.literal_eval(value):
        X.append(i['name'].replace(" ",''))
        count += 1
        if count == 3:
            break
    return X

def getDirector(value):
    director = ast.literal_eval(value)
    X = []
    for i in director:
        if i['job'].lower() == 'director':
            X.append(i['name'].replace(" ",''))
            break
    return X

In [48]:
movies = pd.read_csv("Movies.csv",converters={
    'genres':convert,
    'keywords':convert,
    'overview':convertOverview
})
credit = pd.read_csv("Credits.csv",converters={
    'cast':convert3,
    'crew':getDirector
})


In [49]:
credit_new = pd.read_csv("Credits.csv")

In [50]:
movies

budget                                        genres   
0     237000000  [Action, Adventure, Fantasy, ScienceFiction]  \
1     300000000                  [Adventure, Fantasy, Action]   
2     245000000                    [Action, Adventure, Crime]   
3     250000000              [Action, Crime, Drama, Thriller]   
4     260000000           [Action, Adventure, ScienceFiction]   
...         ...                                           ...   
4798     220000                     [Action, Crime, Thriller]   
4799       9000                             [Comedy, Romance]   
4800          0             [Comedy, Drama, Romance, TVMovie]   
4801          0                                            []   
4802          0                                 [Documentary]   

                                               homepage      id   
0                           http://www.avatarmovie.com/   19995  \
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language   
0     [cultureclash, future, spacewar, spacecolony, ...                en  \
1     [ocean, drugabuse, exoticisland, eastindiatrad...                en   
2     [spy, basedonnovel, secretagent, sequel, mi6, ...                en   
3     [dccomics, crimefighter, terrorist, secretiden...                en   
4     [basedonnovel, mars, medallion, spacetravel, p...                en   
...                                                 ...               ...   
4798  [unitedstates–mexicobarrier, legs, arms, paper...                es   
4799                                                 []                en   
4800  [date, loveatfirstsight, narration, investigat...                en   
4801                                                 []                en   
4802           [obsession, camcorder, crush, dreamgirl]                en   

                                original_title   
0                                       Avatar  \
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                               overview  popularity   
0     [In, the, 22nd, century,, a, paraplegic, Marin...  150.437577  \
1     [Captain, Barbossa,, long, believed, to, be, d...  139.082615   
2     [A, cryptic, message, from, Bond’s, past, send...  107.376788   
3     [Following, the, death, of, District, Attorney...  112.312950   
4     [John, Carter, is, a, war-weary,, former, mili...   43.926995   
...                                                 ...         ...   
4798  [El, Mariachi, just, wants, to, play, his, gui...   14.269792   
4799  [A, newlywed, couple's, honeymoon, is, upended...    0.642552   
4800  ["Signed,, Sealed,, Delivered", introduces, a,...    1.444476   
4801  [When, ambitious, New, York, attorney, Sam, is...    0.857008   
4802  [Ever, since, the, second, grade, when, he, fi...    1.929883   

                                   productio

In [51]:
credit_new.isnull().sum()

movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [52]:
credit.isnull().sum()

movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [53]:
movies = movies.merge(credit,on='title')

In [54]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [55]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [56]:
movies['tags'] = movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [57]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
tags        0
dtype: int64

In [58]:
movies['tags']

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...                        
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: tags, Length: 4809, dtype: object

In [59]:
movies['tags'] = movies['tags'].apply(lambda x:" ".join(x).lower())

In [62]:
movies 

movie_id                                     title   
0        19995                                    Avatar  \
1          285  Pirates of the Caribbean: At World's End   
2       206647                                   Spectre   
3        49026                     The Dark Knight Rises   
4        49529                               John Carter   
...        ...                                       ...   
4804      9367                               El Mariachi   
4805     72766                                 Newlyweds   
4806    231617                 Signed, Sealed, Delivered   
4807    126186                          Shanghai Calling   
4808     25975                         My Date with Drew   

                                               overview   
0     [In, the, 22nd, century,, a, paraplegic, Marin...  \
1     [Captain, Barbossa,, long, believed, to, be, d...   
2     [A, cryptic, message, from, Bond’s, past, send...   
3     [Following, the, death, of, District, Attorney...   
4     [John, Carter, is, a, war-weary,, former, mili...   
...                                                 ...   
4804  [El, Mariachi, just, wants, to, play, his, gui...   
4805  [A, newlywed, couple's, honeymoon, is, upended...   
4806  ["Signed,, Sealed,, Delivered", introduces, a,...   
4807  [When, ambitious, New, York, attorney, Sam, is...   
4808  [Ever, since, the, second, grade, when, he, fi...   

                                            genres   
0     [Action, Adventure, Fantasy, ScienceFiction]  \
1                     [Adventure, Fantasy, Action]   
2                       [Action, Adventure, Crime]   
3                 [Action, Crime, Drama, Thriller]   
4              [Action, Adventure, ScienceFiction]   
...                                            ...   
4804                     [Action, Crime, Thriller]   
4805                             [Comedy, Romance]   
4806             [Comedy, Drama, Romance, TVMovie]   
4807                                            []   
4808                                 [Documentary]   

                                               keywords   
0     [cultureclash, future, spacewar, spacecolony, ...  \
1     [ocean, drugabuse, exoticisland, eastindiatrad...   
2     [spy, basedonnovel, secretagent, sequel, mi6, ...   
3     [dccomics, crimefighter, terrorist, secretiden...   
4     [basedonnovel, mars, medallion, spacetravel, p...   
...                                                 ...   
4804  [unitedstates–mexicobarrier, legs, arms, paper...   
4805                                                 []   
4806  [date, loveatfirstsight, narration, investigat...   
4807                                                 []   
4808           [obsession, camcorder, crush, dreamgirl]   

                                                cast                crew   
0      [SamWorthington, ZoeSaldana, SigourneyWeaver]      [JamesCameron]  \
1         [JohnnyDepp, OrlandoBloom, KeiraKnightley]     [GoreVerbinski]   
2          [DanielCraig, ChristophWaltz, LéaSeydoux]         [SamMendes]   
3          [ChristianBale, MichaelCaine, GaryOldman]  [ChristopherNolan]   
4        [TaylorKitsch, LynnCollins, SamanthaMorton]     [AndrewStanton]   
...                                              ...                 ...   
4804  [CarlosGallardo, JaimedeHoyos, PeterMarquardt]   [RobertRodriguez]   
4805       [EdwardBurns, KerryBishé, MarshaDietlein]       [EdwardBurns]   
4806         [EricMabius, KristinBooth, CrystalLowe]        [ScottSmith]   
4807          [DanielHenney, ElizaCoupe, BillPaxton]        [DanielHsia]   
4808  [DrewBarrymore, BrianHerzlinger, CoreyFeldman]   [BrianHerzlinger]   

                                                   tags  
0     in the 22nd century, a paraplegic marine is di...  
1     captain barbossa, long believed to be dead, ha...  
2     a cryptic message from bond’s past sends him o...  
3     following the death of district attorney harve...  
4     john cart

In [63]:
data = movies[['movie_id','title','tags']]

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bond’s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...                        
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tags, Length: 4809, dtype: object

In [89]:
data

movie_id                                     title   
0        19995                                    Avatar  \
1          285  Pirates of the Caribbean: At World's End   
2       206647                                   Spectre   
3        49026                     The Dark Knight Rises   
4        49529                               John Carter   
...        ...                                       ...   
4804      9367                               El Mariachi   
4805     72766                                 Newlyweds   
4806    231617                 Signed, Sealed, Delivered   
4807    126186                          Shanghai Calling   
4808     25975                         My Date with Drew   

                                                   tags  
0     in the 22nd century, a paraplegic marine is di...  
1     captain barbossa, long believed to be dead, ha...  
2     a cryptic message from bond’s past sends him o...  
3     following the death of district attorney harve...  
4     john carter is a war-weary, former military ca...  
...                                                 ...  
4804  el mariachi just wants to play his guitar and ...  
4805  a newlywed couple's honeymoon is upended by th...  
4806  "signed, sealed, delivered" introduces a dedic...  
4807  when ambitious new york attorney sam is sent t...  
4808  ever since the second grade when he first saw ...  

[4809 rows x 3 columns]

In [83]:
from nltk.stem.porter import PorterStemmer

In [84]:
ps = PorterStemmer()

In [92]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [94]:
data['tags'] = data['tags'].apply(stem)

C:\Users\DELL\AppData\Local\Temp\ipykernel_11376\2997483169.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tags'] = data['tags'].apply(stem)


In [95]:
from sklearn.feature_extraction.text import CountVectorizer

In [96]:
cv = CountVectorizer(max_features=5000,stop_words='english')

In [97]:
vectors = cv.fit_transform(data['tags']).toarray()


In [101]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [104]:
from sklearn.metrics.pairwise import cosine_similarity

In [107]:
similar = cosine_similarity(vectors)

In [123]:
def recomend(movie):
    index = data[data['title'] == movie].index[0]
    dist = similar[index]
    new_list = sorted(list(enumerate(dist)),reverse =True ,key = lambda x :x[1])[1:6]
    for i in new_list:
        print(data.iloc[i[0]].title)


In [125]:
recomend('Batman')

Batman
Batman & Robin
Batman Begins
Batman Returns
The R.M.
